In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [2]:
import numpy as np
arr=np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [9]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.rand(12)

array([0.96556694, 0.84863027, 0.19798772, 0.22238103, 0.94977126,
       0.8199717 , 0.77069875, 0.55425472, 0.43901923, 0.00657013,
       0.17473471, 0.52087091])

In [12]:
np.random.randn(25)

array([-1.50930802,  0.21435776, -0.43912535,  0.0468436 ,  0.11408125,
        0.0697099 ,  0.25695692, -0.2505693 , -1.14908585, -0.03094915,
        0.36829755, -0.37692968, -0.54620598, -0.77374346, -0.11394841,
       -0.52036759, -0.39183387,  1.40129479, -0.31002823,  0.83900073,
       -0.69551078,  0.38562051,  2.12986979,  2.25442805, -0.13141983])

In [6]:
np.arange(0,1,0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [14]:
arr= np.arange(0.01,1.01,0.01)
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [8]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [16]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [17]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [18]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
a[2,2]

13

In [20]:
a[3,4]

20

In [21]:
a[2,2:5]

array([13, 14, 15])

In [22]:
a[2:5,2]

array([13, 18, 23])

In [23]:
a[2:5,2:5]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [24]:
a[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [25]:
a[:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [26]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [27]:
a[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [28]:
a[3,4]

20

In [29]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [30]:
a[3:,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
np.sum(a)

325

In [32]:
np.std(a)

7.211102550927978

In [33]:
np.sum(a,axis=0)

array([55, 60, 65, 70, 75])

In [34]:
b=np.arange(0,12)
c=b.reshape(3,2,2)
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [35]:
b.dtype

dtype('int32')

In [36]:
c.ndim

3

In [37]:
c.size

12

In [38]:
c.shape

(3, 2, 2)

In [39]:
np.ones(12).reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.zeros(12).reshape(3,2,2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [41]:
Math_Marks= np.random.randint(0,101,20)
Math_Marks

array([78, 49, 80, 36, 39, 74, 86, 63, 21, 33, 51, 14, 75, 71, 93, 36, 68,
        4, 78, 44])

In [42]:
aes = np.sort(Math_Marks)
aes

array([ 4, 14, 21, 33, 36, 36, 39, 44, 49, 51, 63, 68, 71, 74, 75, 78, 78,
       80, 86, 93])

In [43]:
np.flip(aes)

array([93, 86, 80, 78, 78, 75, 74, 71, 68, 63, 51, 49, 44, 39, 36, 36, 33,
       21, 14,  4])

In [44]:
aes[::-1]

array([93, 86, 80, 78, 78, 75, 74, 71, 68, 63, 51, 49, 44, 39, 36, 36, 33,
       21, 14,  4])

In [45]:
aes[0:5]

array([ 4, 14, 21, 33, 36])

In [46]:
ab=aes[:6]=12
ab

12

In [47]:
aes

array([12, 12, 12, 12, 12, 12, 39, 44, 49, 51, 63, 68, 71, 74, 75, 78, 78,
       80, 86, 93])

In [48]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [49]:
np.eye(5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [50]:
np.eye(5).ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [51]:
np.ravel?

In [52]:
v=np.arange(0,9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
n=np.arange(9,12)
n

array([ 9, 10, 11])

In [54]:
np.vstack((v,n))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
np.hstack?

In [56]:
k=np.append(v,[n],axis=0)
k

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
np.hsplit(k,3)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [58]:
np.vsplit(k,4)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [59]:
np.eye(5)+4

array([[5., 4., 4., 4., 4.],
       [4., 5., 4., 4., 4.],
       [4., 4., 5., 4., 4.],
       [4., 4., 4., 5., 4.],
       [4., 4., 4., 4., 5.]])

In [60]:
farr=np.random.uniform(1,20,5)
farr

array([16.59507937,  4.19595482,  5.90520956,  1.71480931,  4.3943359 ])

In [61]:
np.ceil(farr)

array([17.,  5.,  6.,  2.,  5.])

In [62]:
np.floor(farr)

array([16.,  4.,  5.,  1.,  4.])

In [63]:
np.round(farr)

array([17.,  4.,  6.,  2.,  4.])

In [64]:
j=np.random.randint(1,100,25).reshape(5,5)
j

array([[28,  2, 61, 73, 48],
       [22, 77, 52, 27,  5],
       [22, 85, 23, 84, 13],
       [41, 24, 23, 86, 80],
       [43, 39, 68,  8, 49]])

In [65]:
np.max(j,axis=1)

array([73, 77, 85, 86, 68])

In [66]:
np.min(j,axis=1)

array([ 2,  5, 13, 23,  8])

In [67]:
np.std(j,axis=1)

array([25.11254666, 25.19206224, 32.11603961, 27.12489631, 19.4381069 ])

In [68]:
g=np.zeros(10)/0
g

C:\Users\DELL\AppData\Local\Temp\ipykernel_5332\2125462535.py:1: RuntimeWarning: invalid value encountered in divide
  g=np.zeros(10)/0


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [69]:
g[6]=200
g

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [70]:
i=np.arange(100,151)
i

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [71]:
np.flip(i)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [72]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
o=np.array([1,0,2,0,0,4,0,8])
o

array([1, 0, 2, 0, 0, 4, 0, 8])

In [82]:
np.where(o<1)

(array([1, 3, 4, 6], dtype=int64),)

In [83]:
f=np.ones(100).reshape(10,10)
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [86]:
f[1:9,1:9]=0
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [100]:
q = np.random.randint(0,20,9)
q.reshape(3,3)

array([[ 1,  3, 15],
       [18, 12,  2],
       [10, 12,  1]])

In [101]:
p = np.random.randint(0,20,9)
p.reshape(3,3)

array([[16,  6, 10],
       [17,  3,  2],
       [ 9, 11,  6]])

In [103]:
d=q+p
d

array([17,  9, 25, 35, 15,  4, 19, 23,  7])

In [104]:
l=q*p
l

array([ 16,  18, 150, 306,  36,   4,  90, 132,   6])

In [105]:
x=q-p
x

array([-15,  -3,   5,   1,   9,   0,   1,   1,  -5])